name: mintyn-admin-report-ai-service
project: mintyn-project
namespace: sandbox
values: |-
  fullnameOverride: mintyn-admin-report-ai-service
  image: 
    repository: mintfintech/mintyn-admin-report-ai-service:app-1
  namespace: sandbox
  containerPort: 5000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: report-ai
    domain: mintfintech.com
  resources:
    requests:
      memory: "350Mi"
      cpu: "200m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  lProbe:
    enabled: false
    path: /health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: false
    path: /health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  env:
    - name: KUBERNETES_NAMESPACE
      value: sandbox
    - name: DB_NAME
      value: mint_account_db
    - name: DB_PASS
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_PASSWORD
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_USERNAME
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_HOST
    - name: OPENAI_API_KEY
      valueFrom:
        configMapKeyRef:
          name: configs
          key: OPENAI_API_KEY
