name: virtual-account-service
project: mintyn-project
namespace: production
values: |-
  fullnameOverride: virtual-account-service
  image: 
    repository: mintfintech/virtual-account-service:prod-app-4
  namespace: production
  containerPort: 8097
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: api-va-service
    domain: mintfintech.com
  resources:
    requests:
      memory: "400Mi"
      cpu: "150m"
    limits:
      memory: "1200Mi"
      cpu: "600m"
  lProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  envFrom:
    - secretRef:
        name: virtual-account-service
  env:
    - name: VIRTUAL_ACCOUNT_SERVICE_SERVICE_HOST
      value: http://virtual-account-service
    - name: KUBERNETES_NAMESPACE
      value: production
    - name: SPRING_PROFILES_ACTIVE
      value: prod  
    - name: DATABASE_USERNAME
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_USERNAME
    - name: KAFKA_BROKERS_URL
      valueFrom:
        configMapKeyRef:
          name: configs
          key: KAFKA_HOST
    - name: DATABASE_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_PASSWORD
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: configs
          key: DATABASE_URL
    - name: TOKEN_MS_SECRET_KEY
      valueFrom:
        configMapKeyRef:
          name: configs
          key: TOKEN_MS_SECRET
    - name: TOKEN_CLIENT_SECRET_KEY
      valueFrom:
        configMapKeyRef:
          name: configs
          key: TOKEN_CLIENT_SECRET
  volumeMounts:
    - name: config
      mountPath: "/mintyn/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: virtual-account-service
